name: Lint and Build
permissions:
  contents: read
  pull-requests: read
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Code Quality (Lint & Format)
        run: pnpm lint

      - name: Production Build
        run: pnpm build
        env:
          NEXT_PUBLIC_CONN_DETAILS_ENDPOINT: https://dummy.endpoint
          AGENT_NAME: tracy

